name: gVXR-SPIE2024
channels:
    - conda-forge
    - https://software.repos.intel.com/python/conda 
    - ccpi
dependencies:
    - python=3.10
    - ipython
    - ipykernel
    - ipyevents=2.0.1
    - ipympl=0.9.1
    - ipywidgets=7.7.0
    - jupyterlab=3.4
    - mpl-interactions=0.22.0        
    - numpy
    # - cma
    # - libtiff
    # - scikit-image
    # - vtk
    - SimpleITK
    - matplotlib
    - cil=24.1.0
    - tigre
    - astra-toolbox=*=cuda* 
    - k3d
    - algotom
    - pip
    - pip:
        # - pymeshlab
        - git+https://bitbucket.org/spekpy/spekpy_release.git
        - xpecgen
        - gVXR>=2.0.8
        # gVXR from the trunk in the Git repository
        # - git+https://git.code.sf.net/p/gvirtualxray/gitroot

